dist: xenial

language: python

branches:
  except:
    - staging.tmp
    - trying.tmp

addons:
  apt:
    packages:
      - libhdf5-serial-dev # needed when there are no wheels

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.7
      env:
      - TOXENV=py37
    - python: 3.8
      env:
      - TOXENV=py38
    - python: 3.7
      env:
      - TOXENV=flake8
    - python: 3.7
      env:
      - TOXENV=pylint
    - python: 3.7
      env:
      - TOXENV=docs
    - python: 3.7
      env:
      - TOXENV=doctest
    - python: 3.7
      env:
      - TOXENV=check-manifest
    - python: 3.7
      env:
      - TOXENV=checkreadme

before_install:
  - pip install codecov # for coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: hSCLg3E8U2WEW7SVZ4iJcNAwTPS83buKuKzhbdAvCwA7ekHJ3uvfeiMn9gymFZvCPCOppxdNvZ8Nt9/xsmUIuv4GKF6BcQCes0LR8qyrslLkovjw1u5wgP3/I0z+nqZovebMtVi1rx0uOEguPoHJx5h8e1XEcLPR7RTTE73Dg4ShtdU+lLDjulU0naeOk2gVVZFsmrgZYU43YySzu8QUyyjDaW8ipGOhzwBip1VvCEiRGhkO+gMoQ1loh9l3Nm3CcimA3Bwogdyh6pqfzd61cFWd9uYc0oPLqIE+8ZWLg+emqJbFYvmcPPbFWiZM1DQGmhoJByoDsCxBCbD1L+vUBYn9TZUgyRFJJTk3RBX15v+HTfzTt87IluHGoiWvccdiNUsjrN0ENkHjdT3jhO/f5eOUFqKWo3k1pIhYatzN/muzlI/ZRMBxNZ1ff+DlSn3WpOhO7r86WZwdjMbz1DbXYkqXsrJw+Cm1QGHgK9hO34MdN9g062NPP/ENkYuoX3sn/wnAiZMvJQe3POaNU59BK5rWxlPoJgn4FLaVk5io0ryfWa1SABHt5oswD2xdgJNsI5iG8OFFhfrfPdU+/bb4+FhmssUwVZwv801lRGhSkrhAy7dxNcB3a82KjKvVar9fLiLNBWQicp7TdyXf8s113bvCiDxvVGKQJvRKxEbkmiY=
  on:
    tags: true
