# from https://packaging.python.org/en/latest/appveyor/
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
environment:
  matrix:

    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python34-x64"
      TOXENV: "py34"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
      TOXPYTHON: "%PYTHON%\\python.exe"

    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"
      TOXPYTHON: "%PYTHON%\\python.exe"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel pip setuptools"
  - "py -3.5 -m pip install --upgrade wheel pip setuptools"
  - "py -3.5 -m pip install tox codecov"

build: off

test_script:
  - "py -3.5 -m tox"

cache:
  - "%LOCALAPPDATA%\\pip\\Cache"

on_success:
  - "py -3.5 -m codecov"
