steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'
  condition: and(succeeded(), ne(variables['python.version'], 'Pre'))

- script: |
    python -m pip install --upgrade pip
    pip install tox codecov
  displayName: 'Install pip dependencies'

- script: env
  displayName: 'print env'

- script: |
    tox
  displayName: 'tox'

#- script: |
#    codecov
#  displayName: 'codecov'
# hopefully the bash uploader will work
- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'
